seed_everything: null
trainer:
  logger:
    - class_path: pytorch_lightning.loggers.MLFlowLogger
      init_args:
        experiment_name: Sentiment Classification augmented
        tracking_uri: http://localhost:5000

  checkpoint_callback: true
  callbacks:
    # https://pytorch-lightning.readthedocs.io/en/latest/extensions/generated/pytorch_lightning.callbacks.ModelCheckpoint.html?highlight=ModelCheckpoint
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: models/sentiment/
        monitor: val_loss
        save_top_k: 3
        filename: "model-{epoch}-{val_loss:.2f}"
        save_last: True

  default_root_dir: null
  gradient_clip_val: 0.0
  gradient_clip_algorithm: norm
  process_position: 0
  num_nodes: 1
  num_processes: 1
  devices: null
  gpus: 1
  auto_select_gpus: true
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 15
  min_epochs: null
  max_steps: null
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 0.5
  flush_logs_every_n_steps: 100
  log_every_n_steps: 50
  accelerator: null
  sync_batchnorm: false
  precision: 32
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  truncated_bptt_steps: null
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: true
  terminate_on_nan: false
  auto_scale_batch_size: false
  prepare_data_per_node: true
  plugins: null
  amp_backend: native
  amp_level: O2
  distributed_backend: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
model:
  pretrained_model_name_or_path: cardiffnlp/twitter-xlm-roberta-base-sentiment
  lr: 0.00001
  n_classes: 3
data:
  train_data_path: data/train_augmented.csv
  val_data_path: data/val_clean.csv
  batch_size: 1
  num_workers: 8
  model_name: cardiffnlp/twitter-xlm-roberta-base-sentiment
  max_length: 128
  train_transforms: null
  val_transforms: null
  test_transforms: null
  dims: null
